import { useEffect, useState } from 'react';
import {
  View, Text, TextInput, Pressable, ScrollView, StyleSheet,
  ActivityIndicator, Image, Switch, Modal, Dimensions,
} from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useTranslation } from 'react-i18next';
import { ScreenContainer } from '../../../src/components/layout';
import { Button } from '../../../src/components/ui';
import { VideoPreview } from '../../../src/components/ui/VideoPreview';
import { AvailabilityPicker, type AvailabilitySelection } from '../../../src/components/provider/AvailabilityPicker';
import {
  fetchPublicRequestSummary,
  submitProviderQuote,
  submitProviderReport,
  QuoteAlreadySubmittedError,
  RequestNotFoundError,
  RequestClosedError,
  parseRequestToken,
} from '../../../src/services/providerForm';
import type { PublicRequestSummary } from '../../../src/services/providerForm';
import { COLORS } from '../../../src/constants';
import { sanitizeText, sanitizeNumeric } from '../../../src/utils/sanitize';

/**
 * Public quote-submission form for a single service request.
 * Reached by service providers via a personalized link in the WhatsApp
 * notification we send. The link carries the request ID in the path and
 * the provider's phone (and optional name) in query params:
 *   /provider/quote/<requestId>?phone=+972...&n=Provider%20Name
 */
export default function ProviderQuoteScreen() {
  const { t } = useTranslation();
  const params = useLocalSearchParams<{
    requestId: string;
    phone?: string;
    n?: string;
  }>();
  // Twilio interactive templates only permit ONE variable per button URL,
  // so the broker packs both requestId and provider phone into a single
  // path segment like "abc123.972546651088". Split it back out here.
  // Still fall through to the `?phone=` query param for links generated by
  // the older text-only flow.
  const { requestId, providerPhone } = parseRequestToken(
    params.requestId,
    (params.phone || '').trim(),
  );
  const providerName = (params.n || '').trim();

  const [summary, setSummary] = useState<PublicRequestSummary | null>(null);
  // Discriminated load state so the screen can render distinct UIs:
  //   'not_found' -> broken/removed link, offer a "report" CTA
  //   'closed'    -> request ended normally, informational only
  //   string      -> unexpected error, show the raw message (debug aid)
  const [loadError, setLoadError] = useState<'not_found' | 'closed' | string | null>(null);
  const [reportSent, setReportSent] = useState(false);
  const [isReporting, setIsReporting] = useState(false);
  const [reportError, setReportError] = useState<string | null>(null);
  const [price, setPrice] = useState('');
  const [isVisitFee, setIsVisitFee] = useState(false);
  const [availability, setAvailability] = useState<AvailabilitySelection | null>(null);
  const [notes, setNotes] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [alreadySubmitted, setAlreadySubmitted] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [preview, setPreview] = useState<
    | { kind: 'image'; uri: string }
    | { kind: 'video'; uri: string; posterUri?: string }
    | null
  >(null);

  useEffect(() => {
    if (!requestId) return;
    fetchPublicRequestSummary(requestId)
      .then(setSummary)
      .catch((err) => {
        if (err instanceof RequestNotFoundError) setLoadError('not_found');
        else if (err instanceof RequestClosedError) setLoadError('closed');
        else setLoadError(err?.message || 'load_failed');
      });
  }, [requestId]);

  const handleReportBrokenLink = async () => {
    if (isReporting || !requestId) return;
    setIsReporting(true);
    setReportError(null);
    try {
      await submitProviderReport({
        requestId,
        providerPhone: providerPhone || 'unknown',
        reason: 'broken_link',
      });
      setReportSent(true);
    } catch (err: any) {
      setReportError(err?.message || 'report_failed');
    } finally {
      setIsReporting(false);
    }
  };

  const canSubmit =
    !isSubmitting &&
    !submitted &&
    price.trim().length > 0 &&
    availability !== null &&
    providerPhone.length > 0;

  const handleSubmit = async () => {
    if (!canSubmit || !summary) return;
    setIsSubmitting(true);
    setSubmitError(null);
    try {
      await submitProviderQuote({
        requestId: summary.requestId,
        providerPhone,
        providerName: providerName || undefined,
        price: sanitizeNumeric(price.trim()),
        isVisitFee,
        availabilityStartAt: availability!.startIso,
        availabilityEndAt: availability!.endIso,
        availabilityText: availability!.label,
        notes: notes.trim() ? sanitizeText(notes.trim(), 500) : undefined,
      });
      setSubmitted(true);
    } catch (err: any) {
      if (err instanceof QuoteAlreadySubmittedError) {
        // Provider tapped the link again after already sending a quote.
        // Show the dedicated "already submitted" state instead of an error.
        setAlreadySubmitted(true);
      } else {
        setSubmitError(err?.message || 'submit_failed');
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  if (loadError === 'closed') {
    // Request ran its course (customer picked someone or abandoned).
    // Informational only — no action for the provider to take.
    return (
      <ScreenContainer>
        <View style={styles.center}>
          <Ionicons name="information-circle" size={64} color={COLORS.info} />
          <Text style={styles.thankTitle}>{t('providerForm.closedTitle')}</Text>
          <Text style={styles.thankSubtitle}>{t('providerForm.closedSubtitle')}</Text>
        </View>
      </ScreenContainer>
    );
  }

  if (loadError === 'not_found') {
    // Link points at an id we have no record of. Could be a broken/copy-paste
    // error, an expired test link, or a bug. Offer a one-tap report CTA.
    return (
      <ScreenContainer>
        <View style={styles.center}>
          <Ionicons name="help-circle" size={64} color={COLORS.warning} />
          <Text style={styles.thankTitle}>{t('providerForm.notFoundTitle')}</Text>
          <Text style={styles.thankSubtitle}>{t('providerForm.notFoundSubtitle')}</Text>
          {reportSent ? (
            <Text style={[styles.availabilityPreview, { textAlign: 'center' }]}>
              {t('providerForm.notFoundReported')}
            </Text>
          ) : (
            <Pressable
              onPress={handleReportBrokenLink}
              disabled={isReporting}
              style={[styles.retryBtn, isReporting && { opacity: 0.6 }]}
            >
              <Text style={styles.retryText}>
                {isReporting ? '...' : t('providerForm.notFoundReport')}
              </Text>
            </Pressable>
          )}
          {reportError && (
            <Text style={styles.debugText}>{t('providerForm.notFoundReportError')}</Text>
          )}
        </View>
      </ScreenContainer>
    );
  }

  if (loadError) {
    // Unexpected failure (network, 500, etc). Keep debug info + retry.
    return (
      <ScreenContainer>
        <View style={styles.center}>
          <Ionicons name="alert-circle" size={48} color={COLORS.error} />
          <Text style={styles.errorText}>{t('providerForm.requestNotFound')}</Text>
          <Text style={styles.debugText}>
            ID: {requestId || '(empty)'}
          </Text>
          <Text style={styles.debugText}>{loadError}</Text>
          <Pressable
            onPress={() => {
              setLoadError(null);
              fetchPublicRequestSummary(requestId)
                .then(setSummary)
                .catch((err) => {
                  if (err instanceof RequestNotFoundError) setLoadError('not_found');
                  else if (err instanceof RequestClosedError) setLoadError('closed');
                  else setLoadError(err?.message || 'load_failed');
                });
            }}
            style={styles.retryBtn}
          >
            <Text style={styles.retryText}>נסה שוב</Text>
          </Pressable>
        </View>
      </ScreenContainer>
    );
  }

  if (!summary) {
    return (
      <ScreenContainer>
        <View style={styles.center}>
          <ActivityIndicator color={COLORS.primary} size="large" />
        </View>
      </ScreenContainer>
    );
  }

  if (alreadySubmitted) {
    return (
      <ScreenContainer>
        <View style={styles.center}>
          <Ionicons name="information-circle" size={64} color={COLORS.info} />
          <Text style={styles.thankTitle}>{t('providerForm.alreadySubmittedTitle')}</Text>
          <Text style={styles.thankSubtitle}>{t('providerForm.alreadySubmittedSubtitle')}</Text>
        </View>
      </ScreenContainer>
    );
  }

  if (submitted) {
    return (
      <ScreenContainer>
        <View style={styles.center}>
          <Ionicons name="checkmark-circle" size={64} color={COLORS.success} />
          <Text style={styles.thankTitle}>{t('providerForm.submittedTitle')}</Text>
          <Text style={styles.thankSubtitle}>{t('providerForm.submittedSubtitle')}</Text>
        </View>
      </ScreenContainer>
    );
  }

  return (
    <ScreenContainer>
      <ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled">
        <Text style={styles.brandTitle}>ai-fixly</Text>
        <Text style={styles.title}>{t('providerForm.title')}</Text>

        {/* Problem context — read-only summary the provider needs */}
        <View style={styles.card}>
          <Text style={styles.cardLabel}>{t('providerForm.location')}</Text>
          <Text style={styles.cardValue}>{summary.city}</Text>

          <Text style={[styles.cardLabel, { marginTop: 12 }]}>{t('providerForm.problem')}</Text>
          <Text style={styles.cardValue}>{summary.textDescription || '—'}</Text>

          {(() => {
            // Prefer the type-aware list if the broker provided it; fall back
            // to the legacy string[] (treat all as images).
            const items =
              summary.mediaItems && summary.mediaItems.length > 0
                ? summary.mediaItems
                : (summary.mediaUrls || []).map((url) => ({ url, type: 'image' as const }));
            if (items.length === 0) return null;
            return (
              <View style={styles.thumbRow}>
                {items.slice(0, 10).map((item, i) => {
                  const isVideo = item.type === 'video';
                  return (
                    <Pressable
                      key={i}
                      onPress={() =>
                        setPreview(
                          isVideo
                            ? { kind: 'video', uri: item.url, posterUri: item.thumbnailUrl }
                            : { kind: 'image', uri: item.url },
                        )
                      }
                    >
                      {isVideo ? (
                        <View style={styles.videoThumbWrap}>
                          {item.thumbnailUrl ? (
                            <Image source={{ uri: item.thumbnailUrl }} style={styles.thumb} />
                          ) : (
                            <View style={[styles.thumb, styles.videoThumbFallback]} />
                          )}
                          <View style={styles.videoPlayOverlay}>
                            <Ionicons name="play-circle" size={28} color="#FFFFFF" />
                          </View>
                        </View>
                      ) : (
                        <Image source={{ uri: item.url }} style={styles.thumb} />
                      )}
                    </Pressable>
                  );
                })}
              </View>
            );
          })()}
        </View>

        {/* Price */}
        <View style={styles.section}>
          <Text style={styles.label}>{t('providerForm.priceLabel')}</Text>
          <TextInput
            value={price}
            onChangeText={setPrice}
            placeholder={t('providerForm.pricePlaceholder')}
            placeholderTextColor={COLORS.textTertiary}
            keyboardType="numeric"
            style={styles.input}
          />

          <View style={styles.switchRow}>
            <Switch
              value={isVisitFee}
              onValueChange={setIsVisitFee}
              trackColor={{ true: COLORS.primary, false: COLORS.border }}
            />
            <View style={{ flex: 1 }}>
              <Text style={styles.switchLabel}>{t('providerForm.isVisitFee')}</Text>
              <Text style={styles.switchHint}>{t('providerForm.isVisitFeeHint')}</Text>
            </View>
          </View>
        </View>

        {/* Availability */}
        <View style={styles.section}>
          <AvailabilityPicker onChange={setAvailability} />
          {availability && (
            <Text style={styles.availabilityPreview}>
              {t('providerForm.youSelected')}: {availability.label}
            </Text>
          )}
        </View>

        {/* Optional notes */}
        <View style={styles.section}>
          <Text style={styles.label}>{t('providerForm.notesLabel')}</Text>
          <TextInput
            value={notes}
            onChangeText={setNotes}
            placeholder={t('providerForm.notesPlaceholder')}
            placeholderTextColor={COLORS.textTertiary}
            multiline
            style={[styles.input, { minHeight: 80, textAlignVertical: 'top' }]}
          />
        </View>

        {submitError && (
          <Text style={styles.errorText}>{t('providerForm.submitError')}</Text>
        )}

        <Button
          title={t('providerForm.submit')}
          onPress={handleSubmit}
          disabled={!canSubmit}
          isLoading={isSubmitting}
        />

        <Text style={styles.footer}>{t('providerForm.footer')}</Text>
      </ScrollView>

      <Modal visible={!!preview} transparent animationType="fade" onRequestClose={() => setPreview(null)}>
        <View style={styles.previewOverlay}>
          {preview?.kind === 'video' ? (
            <VideoPreview uri={preview.uri} posterUri={preview.posterUri} style={styles.previewVideo} />
          ) : preview ? (
            <Pressable style={styles.previewImageWrap} onPress={() => setPreview(null)}>
              <Image source={{ uri: preview.uri }} style={styles.previewImage} resizeMode="contain" />
            </Pressable>
          ) : null}
          <Pressable style={styles.previewClose} onPress={() => setPreview(null)} hitSlop={10}>
            <Ionicons name="close-circle" size={36} color="#FFFFFF" />
          </Pressable>
        </View>
      </Modal>
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  scroll: { padding: 16, paddingBottom: 60, gap: 16 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, gap: 12 },
  brandTitle: { color: COLORS.primary, fontSize: 14, fontWeight: '700' },
  title: { color: COLORS.text, fontSize: 22, fontWeight: 'bold' as any, marginBottom: 4 },

  card: {
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  cardLabel: { color: COLORS.textTertiary, fontSize: 12, fontWeight: '600' as any },
  cardValue: { color: COLORS.text, fontSize: 15, marginTop: 4 },
  thumbRow: { flexDirection: 'row' as any, flexWrap: 'wrap' as any, gap: 8, marginTop: 12 },
  thumb: { width: 72, height: 72, borderRadius: 8 },
  videoThumbWrap: { position: 'relative', width: 72, height: 72 },
  videoThumbFallback: {
    backgroundColor: '#101015',
    width: 72,
    height: 72,
  },
  videoPlayOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.25)',
    borderRadius: 8,
  },
  previewOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewImageWrap: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewImage: {
    width: Dimensions.get('window').width - 32,
    height: Dimensions.get('window').width - 32,
    borderRadius: 12,
  },
  previewVideo: {
    width: Dimensions.get('window').width - 32,
    height: (Dimensions.get('window').width - 32) * 1.2,
    borderRadius: 12,
    backgroundColor: '#000',
  },
  previewClose: {
    position: 'absolute' as any,
    top: 60,
    right: 20,
  },

  section: { gap: 8 },
  label: { color: COLORS.text, fontSize: 14, fontWeight: '600' as any },
  input: {
    backgroundColor: COLORS.surface,
    color: COLORS.text,
    borderRadius: 10,
    padding: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  switchRow: { flexDirection: 'row' as any, alignItems: 'center', gap: 12, marginTop: 4 },
  switchLabel: { color: COLORS.text, fontSize: 13, fontWeight: '600' as any },
  switchHint: { color: COLORS.textTertiary, fontSize: 12, marginTop: 2 },
  availabilityPreview: { color: COLORS.success, fontSize: 13, fontWeight: '600' as any, marginTop: 8 },

  errorText: { color: COLORS.error, fontSize: 15, textAlign: 'center' as any, fontWeight: '700' as any },
  debugText: { color: COLORS.textTertiary, fontSize: 11, textAlign: 'center' as any, fontFamily: 'monospace' as any },
  retryBtn: { marginTop: 12, backgroundColor: COLORS.primary, paddingHorizontal: 20, paddingVertical: 10, borderRadius: 10 },
  retryText: { color: '#FFFFFF', fontWeight: '700' as any },
  thankTitle: { color: COLORS.text, fontSize: 22, fontWeight: 'bold' as any, marginTop: 12 },
  thankSubtitle: { color: COLORS.textSecondary, fontSize: 14, textAlign: 'center' as any, marginTop: 4 },
  footer: { color: COLORS.textTertiary, fontSize: 11, textAlign: 'center' as any, marginTop: 8 },
});
