/**
 * Workaround for Cloudflare Pages silently dropping any file under a
 * `node_modules/` path. Our Expo web export places the vector-icon TTFs
 * at `dist/assets/node_modules/@expo/.../Fonts/*.ttf`, and after upload
 * those URLs return the SPA index.html instead of the font — meaning
 * every Ionicon renders as an empty square.
 *
 * This script runs after `expo export` and before `wrangler pages
 * deploy`. It:
 *
 *   1. Copies every TTF from the nested node_modules Fonts directory to
 *      a flat, sibling path `dist/static-assets/Fonts/` (no node_modules
 *      in the path — Cloudflare uploads it fine).
 *   2. Writes a `_redirects` file that rewrites the original URLs to the
 *      new location with a 200 (internal rewrite, not a 3xx redirect, so
 *      the font-src CSP keeps working and there is no extra roundtrip).
 *
 * Safe to run multiple times — it overwrites instead of appending.
 */

import * as fs from 'fs';
import * as path from 'path';

const DIST = path.resolve(__dirname, '..', 'dist');
const SRC_DIR = path.join(
  DIST,
  'assets',
  'node_modules',
  '@expo',
  'vector-icons',
  'build',
  'vendor',
  'react-native-vector-icons',
  'Fonts',
);
const DEST_DIR = path.join(DIST, 'static-assets', 'Fonts');
const REDIRECTS_PATH = path.join(DIST, '_redirects');

function copyFonts(): string[] {
  if (!fs.existsSync(SRC_DIR)) {
    console.warn(`[post-build-fonts] source dir missing: ${SRC_DIR}`);
    return [];
  }
  fs.mkdirSync(DEST_DIR, { recursive: true });

  const files = fs.readdirSync(SRC_DIR).filter((f) => f.endsWith('.ttf'));
  for (const file of files) {
    fs.copyFileSync(path.join(SRC_DIR, file), path.join(DEST_DIR, file));
  }
  return files;
}

function writeRedirects(fontFiles: string[]): void {
  // Preserve any existing _redirects content, then append our rules.
  const existing = fs.existsSync(REDIRECTS_PATH) ? fs.readFileSync(REDIRECTS_PATH, 'utf-8') : '';
  const rules = fontFiles.map((name) => {
    const from = `/assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/${name}`;
    const to = `/static-assets/Fonts/${name}`;
    return `${from} ${to} 200`;
  });

  // A wildcard catch-all lets new fonts work without regenerating this file.
  rules.push(
    '/assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/* /static-assets/Fonts/:splat 200',
  );

  const header = '# Auto-generated by scripts/post-build-fonts.ts — do not edit by hand.';
  const next = [existing.trim(), header, ...rules].filter(Boolean).join('\n') + '\n';
  fs.writeFileSync(REDIRECTS_PATH, next, 'utf-8');
}

function main(): void {
  const fonts = copyFonts();
  writeRedirects(fonts);
  console.log(`[post-build-fonts] copied ${fonts.length} fonts + wrote _redirects`);
}

main();
